name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
  run:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run
        run: docker-compose up -d
  checks:
    runs-on: self-hosted
    needs: [build,run]
    steps:
      - name: Check sql
        run: psql -h 127.0.0.1 -d ergodex -U ergodex -c 'SELECT COUNT(*) AS cnt FROM assets;'
        env:
          PGPASSWORD: ergodex
      - name: Check api
        run: curl http://127.0.0.1:8080/api/v1/pools/
  cleanup:
    runs-on: self-hosted
    needs: [build,run,checks]
    steps:
      - name: Stop
        run: docker-compose down
