name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker-compose build
      - name: Run
        run: docker-compose up -d
      - name: Check sql
        run: psql -h postgres -d ergodex -U ergodex -c 'SELECT COUNT(*) AS cnt FROM assets;'
        env:
          PGPASSWORD: ergodex
      - name: Check api
        run: curl http://127.0.0.1:8080/api/v1/pools/
      - name: Stop
        run: docker-compose down
